server:
  port: 8080

app:
  security:
    enabled: true

spring:
  config:
    activate:
      on-profile: keycloak

  security:
    oauth2:
      resourceserver:
        jwt:
          # Validate via JWKS only (matches your compose env/Keycloak service)
          jwk-set-uri: http://keycloak:8080/realms/github-popularity/protocol/openid-connect/certs


springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    config-url: /v3/api-docs/swagger-config
    url: /v3/api-docs
    oauth:
      client-id: github-popularity-api
      use-pkce-with-authorization-code-grant: true
      scopes: openid,profile
    oauth2-redirect-url: http://localhost:8080/swagger-ui/oauth2-redirect.html


github:
  api:
    base-url: https://api.github.com
    version: 2022-11-28

popularity:
  score:
    stars-weight: 0.6
    forks-weight: 0.25
    recency-weight: 0.15
    recency-half-life-days: 90
