server:
  port: 8080

springdoc:
  api-docs:
    path: /~/github-popularity-score-service/api-docs
  swagger-ui:
    operationsSorter: alpha
    tagsSorter: alpha

github:
  api:
    base-url: https://api.github.com
  api-version: 2022-11-28
  token: ${GITHUB_TOKEN:}
  client:
    max-in-memory-size: 16777216
  cache:
    ttl-minutes: 5

scoring:
  stars-weight: 0.6
  forks-weight: 0.25
  recency-weight: 0.15
  recency-half-life-days: 30
