server:
  port: 8080

app:
  auth:
    enabled: false

# localhost:8180 -> use when testing outside docker container
spring:
  security:
    oauth2:
      client:
        provider:
          keycloak:
            authorization-uri: http://host.docker.internal:8180/realms/github-popularity/protocol/openid-connect/auth
            token-uri:         http://host.docker.internal:8180/realms/github-popularity/protocol/openid-connect/token
      resourceserver:
        jwt:
          jwk-set-uri:        http://host.docker.internal:8180/realms/github-popularity/protocol/openid-connect/certs
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    config-url: /v3/api-docs/swagger-config
    url: /v3/api-docs
    oauth:
      client-id: github-popularity-api
      use-pkce-with-authorization-code: true
      scopes: openid,profile

github:
  api:
    base-url: https://api.github.com
    version: 2022-11-28

popularity:
  score:
    stars-weight: 0.6
    forks-weight: 0.25
    recency-weight: 0.15
    recency-half-life-days: 90
