server:
  port: 8080

app:
  auth:
    enabled: false

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8180/realms/github-popularity
      client:
        registration:
          keycloak:
            client-id: github-popularity-api
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/swagger-ui/oauth2-redirect.html"
            scope: [openid, profile]
        provider:
          keycloak:
            issuer-uri: http://localhost:8180/realms/github-popularity

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    config-url: /v3/api-docs/swagger-config
    url: /v3/api-docs
    oauth:
      client-id: github-popularity-api
      use-pkce-with-authorization-code: true
      scopes: openid,profile

github:
  api:
    base-url: https://api.github.com
    version: 2022-11-28

popularity:
  score:
    stars-weight: 0.6
    forks-weight: 0.25
    recency-weight: 0.15
    recency-half-life-days: 90
