server:
  port: 8080

springdoc:
  api-docs:
    path: /~/github-popularity-score-service/api-docs
  swagger-ui:
    operationsSorter: alpha
    tagsSorter: alpha

github:
  api:
    base-url: https://api.github.com

popularity:
  score:
    stars-weight: 0.6
    forks-weight: 0.25
    recency-weight: 0.15
    recency-half-life-days: 90
