server:
  port: 8080

app:
  auth:
    enabled: false   # default OFF (no Keycloak, no login)

springdoc:
  swagger-ui:
    oauth2-redirect-url: http://localhost:8080/swagger-ui/oauth2-redirect.html
    oauth:
      use-pkce-with-authorization-code-grant: true

github:
  api:
    base-url: https://api.github.com
    version: 2022-11-28

popularity:
  score:
    stars-weight: 0.6
    forks-weight: 0.25
    recency-weight: 0.15
    recency-half-life-days: 90
